import { IFile } from '@/contexts/files-context'

export const FILES: IFile[] = [
  {
    // the id is generated by crypto.randomUUID()
    id: '63f6794d-6158-424f-8cf4-7d03b1b9f48c',
    name: 'file-1',
    content: `
USE sp500insight;
SELECT sector, industry, COUNT(*) AS companies
FROM companies c
WHERE c.stock_symbol IN (SELECT stock_symbol FROM index_compositions WHERE index_symbol = "SP500")
GROUP BY sector, industry
ORDER BY sector, companies DESC;
`
  },
  {
    id: 'd7692e17-b97d-4342-a6b7-a5e6e4d50021',
    name: 'file-2',
    content: `
USE sp500insight;
SELECT
    sector,
    COUNT(*) AS companies,
    SUM(market_cap) AS total_market_cap,
    AVG(revenue_growth) AS avg_revenue_growth
FROM companies c
WHERE
    stock_symbol IN (SELECT stock_symbol FROM index_compositions WHERE index_symbol = 'SP500')
GROUP BY sector
ORDER BY avg_revenue_growth DESC;
`
  },
  {
    id: '64c80ed3-f7b4-4959-9520-ad92706aa815',
    name: 'file-3',
    content: `
USE sp500insight;
SELECT
    ic.stock_symbol,
    c.short_name,
    ic.weight,
    c.market_cap
  FROM
    index_compositions ic
    JOIN companies c ON ic.stock_symbol = c.stock_symbol
  WHERE
    ic.index_symbol = 'SP500'
  ORDER BY
    ic.weight DESC;
`
  },
  {
    id: '838e098a-752e-445d-bccb-6262c4529378',
    name: 'file-4',
    content: `
USE game;
With r AS (
    SELECT
        games.name,
        genre.genre_name,
        rank() over (partition by genre.genre_id order by games.metacritic_score desc) as ranking
    FROM game_genre gg
    LEFT JOIN genre ON genre.genre_id = gg.genre_id
    LEFT JOIN games ON games.app_id = gg.app_id
    WHERE games.metacritic_score != 0
)
SELECT *
FROM r
WHERE r.ranking <= 5;
`
  },
  {
    id: 'f0e3f7d4-1a1c-4c0e-9e9b-6f5b7e7d8d4d',
    name: 'file-5',
    content: `
USE game;
SELECT name, average_playtime_forever
FROM games
ORDER BY average_playtime_forever DESC
LIMIT 10;
`
  },
  {
    id: '0ff8cf7c-fca3-45df-a275-e079d15ba90e', // generated by crypto.randomUUID()
    name: 'file-6',
    content: `
USE game;
SELECT g.*
FROM game_genre gg
LEFT JOIN games g ON g.app_id = gg.app_id
WHERE gg.genre_id  = 9
ORDER BY g.estimated_owners DESC;
`
  },
  {
    id: '64c80ed3-f7b4-4959-9520-ad92706aa817',
    name: 'file-7',
    content: ``
  }
]
