name: Test Published Packages

on:
  push:
    branches:
      - test-published-packages

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Build Package
        run: pnpm build:playground
