name: Test Published Packages

on:
  push:
    branches:
      - test-published-packages

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @tidbcloud:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$PKG_TOKEN
          EOF
        env:
          PKG_TOKEN: ${{ secrets.PKG_TOKEN }}

      - name: Install Dependencies
        run: pnpm i

      - name: Build Playground
        run: pnpm build:playground
